### ISSUE TITLE
Simplifications for SimpleActivity sample

### ISSUE THREAD

**Issue by keyboardsurfer** [mikescamell/shared-element-transitions#2]
In your [SimpleActivity example](https://github.com/mikescamell/shared-element-transitions/blob/master/app/src/main/java/com/mikescamell/sharedelementtransitions/simple_activity_to_activity/SimpleActivityA.java#L30) you're setting matching transition names in different ([A](https://github.com/mikescamell/shared-element-transitions/blob/master/app/src/main/res/layout/activity_a.xml#L22) / [B](https://github.com/mikescamell/shared-element-transitions/blob/master/app/src/main/res/layout/activity_b.xml#L16) and [strings.xml](https://github.com/mikescamell/shared-element-transitions/blob/master/app/src/main/res/values/strings.xml#L4)) ways.
Instead of doing this you can pass in `imageView.getTransitionName()` into the last param the of [ActivityOptionsCompat](https://github.com/mikescamell/shared-element-transitions/blob/master/app/src/main/java/com/mikescamell/sharedelementtransitions/simple_activity_to_activity/SimpleActivityA.java#L30) call.

This simplification can be made in several examples.

**Comment by mikescamell** [comment]
@keyboardsurfer you're correct I've been inconsistent with how I've set things. 

The `SimpleActivityA` xml layout was because I wanted the code to be more obvious, but I guess that people should have some experience with Android if they're reading!

The reason I don't call `imageView.getTransitionName()` is because I dislike having to wrap things with `if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP)`. If I use a `strings.xml` or a string it means I don't have to have it in my code.

**Comment by nickbutcher** [comment]
https://developer.android.com/reference/android/support/v4/view/ViewCompat.html#getTransitionName(android.view.View)
?

**Comment by mikescamell** [comment]
Am i missing something @nickbutcher? If I call `imageView.getTransitionName()` on API 19 it will crash right?

**Comment by nickbutcher** [comment]
That call would crash which is why I was suggesting calling
`ViewCompat.getTransitionName(imageView)` instead which will API check for
you, or return null.

**Comment by mikescamell** [comment]
Ah ok gotcha! Don't think I've ever had to call `ViewCompat` that I can remember 🤔 Looks like I'll be using it more often from now on 😄  Thanks for the tip.

**Comment by mikescamell** [comment]
The code has now been adjusted to take these comments into account. Thanks again for the suggestions.
