### ISSUE TITLE
New Fragment added on top of previous one each time the activity is recreated

### ISSUE THREAD

**Issue by cbeyls** [mikescamell/shared-element-transitions#6]
In [`RecyclerViewToFragmentActivity`](https://github.com/mikescamell/shared-element-transitions/blob/master/app/src/main/java/com/mikescamell/sharedelementtransitions/recycler_view/recycler_view_to_fragment/RecyclerViewToFragmentActivity.java) you add the fragment but you don't test if `savedInstanceState` is `null` first.

When re-creating the Activity, a new fragment will be added on top of the previous one because you used `add()` and not `replace()`.
It's recommended to add it once, when `savedInstanceState` is `null`.

**Comment by mikescamell** [comment]
This has been fixed in #5. It will be merged when I have time to update the changed code in the blog posts.

**Comment by cbeyls** [comment]
I missed that one, thank you for the fix :)
